version: '3.7'

services:
  consul:
    image: consul:latest
    container_name: consul
    restart: unless-stopped
    ports:
      - 8500:8500
    networks:
      - lapka

  fabio:
    image: fabiolb/fabio:latest
    container_name: fabio
    restart: unless-stopped
    environment:
      - FABIO_REGISTRY_CONSUL_ADDR=consul:8500
    ports:
      - 9998:9998
      - 9999:9999
    networks:
      - lapka

  mongo:
    image: mongo
    container_name: mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db
    networks:
      - lapka

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - 5672:5672
      - 15672:15672
      - 15692:15692
    networks:
      - lapka

  seq:
    image: datalust/seq
    container_name: seq
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:80

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    container_name: elastic
    environment:
      - discovery.type=single-node
    volumes:
      - elasticsearch:/data
    ports:
      - 9200:9200
    networks:
      - lapka
      
networks:
  lapka:
    name: lapka

volumes:
  consul:
    driver: local
  mongo:
    driver: local
  rabbitmq:
    driver: local
  seq:
    driver: local
  elasticsearch:
    driver: local
    
